spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_marketplace
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWRldi11c2Utb25seQ==
jwt.expiration-ms=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080